//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDictionary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDictionary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string AddRelationPlaceholder {
            get {
                return ResourceManager.GetString("AddRelationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot play the sound: &quot;{0}&quot;
        ///
        ///{1}.
        /// </summary>
        internal static string CannotPlaySound {
            get {
                return ResourceManager.GetString("CannotPlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot refresh the sound: &quot;{0}&quot;
        ///
        ///{1}.
        /// </summary>
        internal static string CannotRefreshSound {
            get {
                return ResourceManager.GetString("CannotRefreshSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All not saved changes will be discard!.
        /// </summary>
        internal static string ChangesDiscardingWarning {
            get {
                return ResourceManager.GetString("ChangesDiscardingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the answer.
        /// </summary>
        internal static string CheckLabel {
            get {
                return ResourceManager.GetString("CheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} selected clause[s]?.
        /// </summary>
        internal static string ClausesDeletionConfirmation {
            get {
                return ResourceManager.GetString("ClausesDeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct: {0}.
        /// </summary>
        internal static string CorrectLabel {
            get {
                return ResourceManager.GetString("CorrectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new empty dictionary.
        /// </summary>
        internal static string CreateNewDBTitle {
            get {
                return ResourceManager.GetString("CreateNewDBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors occurred during import.
        /// </summary>
        internal static string CSVImportReportTitle {
            get {
                return ResourceManager.GetString("CSVImportReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///DROP TABLE IF EXISTS &quot;TrainingStatistics&quot;;
        ///CREATE TABLE IF NOT EXISTS &quot;TrainingStatistics&quot; (
        ///	&quot;TestType&quot;	INTEGER NOT NULL,
        ///	&quot;ClauseId&quot;	INTEGER NOT NULL,
        ///	&quot;Success&quot;	INTEGER NOT NULL,
        ///	&quot;Fail&quot;	INTEGER NOT NULL,
        ///	&quot;LastTraining&quot;	TEXT NOT NULL,
        ///	PRIMARY KEY(&quot;TestType&quot;,&quot;ClauseId&quot;),
        ///	FOREIGN KEY(&quot;ClauseId&quot;) REFERENCES &quot;Clauses&quot;(&quot;Id&quot;) ON DELETE CASCADE ON UPDATE CASCADE
        ///);
        ///DROP TABLE IF EXISTS &quot;Clauses&quot;;
        ///CREATE TABLE IF NOT EXISTS &quot;Clauses&quot; (
        ///	&quot;Id&quot;	INTEGER NOT NULL PRIMARY KEY AUTOINC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DictionaryDB {
            get {
                return ResourceManager.GetString("DictionaryDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured!.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} (the maximal count) out of {1} relations have been shown..
        /// </summary>
        internal static string ExceedMaxCountOfRelations {
            get {
                return ResourceManager.GetString("ExceedMaxCountOfRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} (the maximal count) out of {1} translations have been shown..
        /// </summary>
        internal static string ExceedMaxCountOfTranslations {
            get {
                return ResourceManager.GetString("ExceedMaxCountOfTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export shown words to a CSV file.
        /// </summary>
        internal static string ExportToCSVTitle {
            get {
                return ResourceManager.GetString("ExportToCSVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export shown words to a Html file.
        /// </summary>
        internal static string ExportToHtmlTitle {
            get {
                return ResourceManager.GetString("ExportToHtmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not found!.
        /// </summary>
        internal static string FileNotFoundError {
            get {
                return ResourceManager.GetString("FileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data was successively imported.
        /// </summary>
        internal static string FileWasSuccessivelyLoaded {
            get {
                return ResourceManager.GetString("FileWasSuccessivelyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was successively saved.
        /// </summary>
        internal static string FileWasSuccessivelySaved {
            get {
                return ResourceManager.GetString("FileWasSuccessivelySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only clauses that are shown according to the current filter will be saved. To save all clauses, it&apos;s needed to clear the filter first.
        ///
        ///Continue and save only filtered clauses?.
        /// </summary>
        internal static string FilterIsActivated {
            get {
                return ResourceManager.GetString("FilterIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string FinishLabel {
            get {
                return ResourceManager.GetString("FinishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ready!.
        /// </summary>
        internal static string GetReadyLabel {
            get {
                return ResourceManager.GetString("GetReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move these {1} selected clause[s] to the group &quot;{0}&quot;?.
        /// </summary>
        internal static string GroupChangeConfirmation {
            get {
                return ResourceManager.GetString("GroupChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.
        /// </summary>
        internal static string IDontKnowLabel {
            get {
                return ResourceManager.GetString("IDontKnowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes were made because of errors. Please rectify errors that shown below and retry import again..
        /// </summary>
        internal static string ImportErrorsMsg {
            get {
                return ResourceManager.GetString("ImportErrorsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import words from a CSV file.
        /// </summary>
        internal static string ImportFromCSVTitle {
            get {
                return ResourceManager.GetString("ImportFromCSVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention please!.
        /// </summary>
        internal static string InformationCaption {
            get {
                return ResourceManager.GetString("InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDictionary.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mistakes: {0}.
        /// </summary>
        internal static string MistakesLabel {
            get {
                return ResourceManager.GetString("MistakesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next question.
        /// </summary>
        internal static string NextQuestionLabel {
            get {
                return ResourceManager.GetString("NextQuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        internal static string NoAnswer {
            get {
                return ResourceManager.GetString("NoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start the training, not enough words.
        ///
        ///Must be at least {0} word[s] in the dictionary and at least {1} word[s] selected for the training..
        /// </summary>
        internal static string NotEnoughWords {
            get {
                return ResourceManager.GetString("NotEnoughWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start the training, not enough words with the sound links.
        ///
        ///Must be at least {0} word[s] with the sound link[s] selected for the training..
        /// </summary>
        internal static string NotEnoughWordsWithSounds {
            get {
                return ResourceManager.GetString("NotEnoughWordsWithSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no training statistic yet..
        /// </summary>
        internal static string NoTrainingStatYet {
            get {
                return ResourceManager.GetString("NoTrainingStatYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the dictionary.
        /// </summary>
        internal static string OpenDictionaryTitle {
            get {
                return ResourceManager.GetString("OpenDictionaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjective.
        /// </summary>
        internal static string POFFullAdjective {
            get {
                return ResourceManager.GetString("POFFullAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adverb.
        /// </summary>
        internal static string POFFullAdverb {
            get {
                return ResourceManager.GetString("POFFullAdverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conjunction.
        /// </summary>
        internal static string POFFullConjunction {
            get {
                return ResourceManager.GetString("POFFullConjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interjection.
        /// </summary>
        internal static string POFFullInterjection {
            get {
                return ResourceManager.GetString("POFFullInterjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noun.
        /// </summary>
        internal static string POFFullNoun {
            get {
                return ResourceManager.GetString("POFFullNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preposition.
        /// </summary>
        internal static string POFFullPreposition {
            get {
                return ResourceManager.GetString("POFFullPreposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pronoun.
        /// </summary>
        internal static string POFFullPronoun {
            get {
                return ResourceManager.GetString("POFFullPronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string POFFullUnknown {
            get {
                return ResourceManager.GetString("POFFullUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verb.
        /// </summary>
        internal static string POFFullVerb {
            get {
                return ResourceManager.GetString("POFFullVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string POFShortAdjective {
            get {
                return ResourceManager.GetString("POFShortAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adv.
        /// </summary>
        internal static string POFShortAdverb {
            get {
                return ResourceManager.GetString("POFShortAdverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cj.
        /// </summary>
        internal static string POFShortConjunction {
            get {
                return ResourceManager.GetString("POFShortConjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int.
        /// </summary>
        internal static string POFShortInterjection {
            get {
                return ResourceManager.GetString("POFShortInterjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string POFShortNoun {
            get {
                return ResourceManager.GetString("POFShortNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prep.
        /// </summary>
        internal static string POFShortPreposition {
            get {
                return ResourceManager.GetString("POFShortPreposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pron.
        /// </summary>
        internal static string POFShortPronoun {
            get {
                return ResourceManager.GetString("POFShortPronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string POFShortUnknown {
            get {
                return ResourceManager.GetString("POFShortUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        internal static string POFShortVerb {
            get {
                return ResourceManager.GetString("POFShortVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention please!.
        /// </summary>
        internal static string QuestionCaption {
            get {
                return ResourceManager.GetString("QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file was not found. The link will be removed from the list..
        /// </summary>
        internal static string RecentLinkWillBeRemoved {
            get {
                return ResourceManager.GetString("RecentLinkWillBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; relations.
        /// </summary>
        internal static string RelationsFilterTextTmpl {
            get {
                return ResourceManager.GetString("RelationsFilterTextTmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right answers: {0} out of {1} ({2}%).
        /// </summary>
        internal static string RightTestAnswers {
            get {
                return ResourceManager.GetString("RightTestAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sound file for the word.
        /// </summary>
        internal static string SelectSoundFileTitle {
            get {
                return ResourceManager.GetString("SelectSoundFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the options.
        /// </summary>
        internal static string ShowTheOptionsLabel {
            get {
                return ResourceManager.GetString("ShowTheOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        internal static string TestTypeListening {
            get {
                return ResourceManager.GetString("TestTypeListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint.
        /// </summary>
        internal static string TestTypeSprint {
            get {
                return ResourceManager.GetString("TestTypeSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation - Word.
        /// </summary>
        internal static string TestTypeTranslationWord {
            get {
                return ResourceManager.GetString("TestTypeTranslationWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Constructor.
        /// </summary>
        internal static string TestTypeWordConstructor {
            get {
                return ResourceManager.GetString("TestTypeWordConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word - Translation.
        /// </summary>
        internal static string TestTypeWordTranslation {
            get {
                return ResourceManager.GetString("TestTypeWordTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &quot;{0}&quot; clause?.
        /// </summary>
        internal static string TheClauseDeletionConfirmation {
            get {
                return ResourceManager.GetString("TheClauseDeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The training is not finished yet, do you want to stop it and close the window?.
        /// </summary>
        internal static string TrainingIsNotFinishedWarning {
            get {
                return ResourceManager.GetString("TrainingIsNotFinishedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched: {0:yyyy-MM-dd} ({1}).
        /// </summary>
        internal static string WatchedDateCount {
            get {
                return ResourceManager.GetString("WatchedDateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitely known.
        /// </summary>
        internal static string WGDefinitelyKnown {
            get {
                return ResourceManager.GetString("WGDefinitelyKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind of known.
        /// </summary>
        internal static string WGKindOfKnown {
            get {
                return ResourceManager.GetString("WGKindOfKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to memorize.
        /// </summary>
        internal static string WGNeedToMemorize {
            get {
                return ResourceManager.GetString("WGNeedToMemorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totally unknown.
        /// </summary>
        internal static string WGTotallyUnknown {
            get {
                return ResourceManager.GetString("WGTotallyUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well known.
        /// </summary>
        internal static string WGWellKnown {
            get {
                return ResourceManager.GetString("WGWellKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1}, that&apos;s great!.
        /// </summary>
        internal static string WithoutErrorsMessage {
            get {
                return ResourceManager.GetString("WithoutErrorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word &quot;{0}&quot; already presents in the dictionary..
        /// </summary>
        internal static string WordAlreadyPresents {
            get {
                return ResourceManager.GetString("WordAlreadyPresents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; relation to:.
        /// </summary>
        internal static string WordRelationTo {
            get {
                return ResourceManager.GetString("WordRelationTo", resourceCulture);
            }
        }
    }
}
